name: Docker

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile

      - name: Log into registry
        run: echo "${{ secrets.docker_password }}" | docker login -u ${{ secrets.docker_username }} --password-stdin

      - name: Push image
        run: |
          docker tag image ${GITHUB_REPOSITORY,,}:latest
          docker push ${GITHUB_REPOSITORY,,}

